### ISSUE TITLE
Trochę poprawek

### ISSUE THREAD

**Issue by lemielek** [HackerspaceKRK/faq-radiowe#11]
Jeszcze nie wiem jak zrobić diffa w GITcie.

Jeszcze kilka drobiazgów. Nowy załącznik.
[radio_faq1_poprawki_RLI_v2.zip](https://github.com/HackerspaceKRK/faq-radiowe/files/5798660/radio_faq1_poprawki_RLI_v2.zip)

**Comment by canislupus11** [comment]
Wprowadzone. Dzięki!
