### ISSUE TITLE
propozycje zmian od SP8MRD

### ISSUE THREAD

**Issue by lemielek** [HackerspaceKRK/faq-radiowe#16]
Podesłałem mu plik w odt. Zwrotka w docx.
[Krótkofalarstwo w pytaniach i odpowiedziach.docx](https://github.com/HackerspaceKRK/faq-radiowe/files/5825988/Krotkofalarstwo.w.pytaniach.i.odpowiedziach.docx)

**Comment by lemielek** [comment]
Pomysł Piotra na grafikę:
_Co do grafiki, to przyszedł mi do głowy pomysł, aby wstawić linki do konkretnych stron przedstawiających opisywane zagadnienie – to by mogło załatwić temat praw autorskich._

**Comment by canislupus11** [comment]
Linki do stron od grafik nie załatwiają sprawy praw autorskich. 
Co do korekty, przeczytam w wolnej chwili, ale już widzę, ze korekta oparta jest o starą wersję dokumentu, aktualnie większość z błeðów jest juz poprawiona a zmiany w treści będa problematyczne.

**Comment by canislupus11** [comment]
Kilka uwag do zaproponowanych zmian:

??? - Człowiek nie posiada znaku, nie wiem co w tym dziwnego.
(wersja robocza) - czemu? to nie jest wersja robocza, traktujmy to jak rolling release.
Kraków, 16 stycznia 2021 r. - data była, czemu akurat Kraków? Teksty pochodzą z różnych stron Polski i nie tylko. 
Często w ramach pozwolenia dodatkowego krótkofalowcy posiadają znak używany TYLKO podczas zawodów. - nie nie tylko. bo czemu tylko?
Należy zaznaczyć, że bandplan to nie jest prawo to raczej społeczna umowa, której powinniśmy przestrzegać, aby żyło nam się lepiej.  BZDURA, brak wiedzy?
 - chęnie poznam podstawę prawna bandplanu. Wtedy zmienię. 
 
 Uwagi językowe itp w większości wrzuciłem do dokumentu. Dziękuję :D
